var AIS_VERSION="ais.adultswim.4";var cnnad_transactionID=null;function cnnad_getTransactionID(){if(cnnad_transactionID==null){cnnad_transactionID="";cnnad_transactionID=Math.round((new Date).getTime()/1E3)+""+Math.floor(Math.random()*9007199254740992)}return cnnad_transactionID}cnnad_getTransactionID();
function cnnad_readCookie(name){if(document.cookie=="")return null;else{var ca=document.cookie.split(";");var nameEQ=name+"=";for(var i=0;i<ca.length;i++){var c=ca[i];while(c.charAt(0)==" ")c=c.substring(1,c.length);if(c.indexOf(nameEQ)==0)return c.substring(nameEQ.length,c.length)}return null}}function cnnad_haveCookie(a){return document.cookie&&(-1<document.cookie.indexOf("; "+a+"=")||document.cookie.indexOf(a+"=")==0)}
function cnnad_ugsync(){if(!cnnad_haveCookie("ugs"))document.write("<scr"+'ipt src="http://www.ugdt'+'urner.com/xd.sjs"></scr'+"ipt>")}cnnad_ugsync();window.Krux||((Krux=function(){Krux.q.push(arguments)}).q=[]);
(function(){var k=document.createElement("script");k.type="text/javascript";k.async=true;var m,src=(m=location.href.match(/\bkxsrc=([^&]+)/))&&decodeURIComponent(m[1]);k.src=/^https?:\/\/([^\/]+\.)?krxd\.net(:\d{1,5})?\//i.test(src)?src:src==="disable"?"":(location.protocol==="https:"?"https:":"http:")+"//cdn.krxd.net/controltag?confid=ITb9NmYG";var s=document.getElementsByTagName("script")[0];s.parentNode.insertBefore(k,s)})();window.Krux||((Krux=function(){Krux.q.push(arguments)}).q=[]);
window.kvs=[];(function getKruxData(){function retrieve(n){var m,k="kx"+n;if(window.localStorage)return window.localStorage[k]||"";else if(navigator.cookieEnabled){m=document.cookie.match(k+"=([^;]*)");return m&&unescape(m[1])||""}else return""}Krux.user=retrieve("user");Krux.segments=retrieve("segs")&&retrieve("segs").split(",")||[];for(var i=0;i<Krux.segments.length;i++)if(kvs.length<20)kvs.push(Krux.segments[i])})();
function krux_getDESegments(){var segmentString="&kxid=";if(Krux.user)segmentString+=Krux.user;segmentString+="&kxseg="+kvs.join(",");return segmentString}function krux_getFWSegments(){return"kxseg="+kvs.join(",kxseg=")}function turner_getTransactionId(){return cnnad_transactionID}function turner_getGuid(){return cnnad_readCookie("ug")}function krux_getUser(){return Krux.user}
function krux_getFWKeyValues(prefix,limit){var segPrefix=prefix||"_fwu:386123:";var segLimit=limit||35;var fwKVP={};for(var x=0;x<Krux.segments.length;x++)if(x<segLimit)fwKVP[segPrefix+Krux.segments[x]]=1;return fwKVP}(function(){var a=document,b=a.createElement("script"),c=a.getElementsByTagName("head")[0];b.type="text/javascript";b.src="http://c.amazon-adsystem.com/aax2/amzn_ads.js";c.appendChild(b)})();
var AmazonDirectMatchBuy=function(){var arrayProto=Array.prototype;var functionProto=Function.prototype;var objectProto=Object.prototype;var nativeBind=functionProto.bind;var hasOwnProperty=objectProto.hasOwnProperty;var slice=arrayProto.slice;var toString=objectProto.toString;function hasOwn(object,key){return object!=null&&hasOwnProperty.call(object,key)}function isFunction(object){return toString.call(object)==="[object Function]"}function isObject(object){var type=typeof object;return type===
"function"||type==="object"&&!!object}function bind(fn,context){if(!isFunction(fn))throw new TypeError("Bind must be called on a function");if(nativeBind&&fn.bind===nativeBind)return nativeBind.apply(fn,slice.call(arguments,1));var args=slice.call(arguments,2);return function bound(){return fn.apply(context,args.concat(slice.call(arguments)))}}function once(fn){return function(){if(fn){fn.apply(this,arguments);fn=null}}}function logger(){if(isObject(window.console)&&isFunction(window.console.log))window.console.log.apply(window.console,
arguments)}var log=bind(logger,null,"[AmazonDirectMatchBuy]");var amznkey="3159";var timeoutForGetAdsCallback=2E3;var inited=false;var noop=function(){};function isAmazonApiAvailable(){return"amznads"in window&&"getTargeting"in window.amznads&&isFunction(window.amznads.getTargeting)}function requestAdRefresh(fn){var callback=once(fn||noop);if(!isAmazonApiAvailable())return callback.call();try{amznads.getAdsCallback(amznkey,callback,timeoutForGetAdsCallback)}catch(e){log("Exception thrown while requesting Amazon ads:",
e);callback.call()}}function getTargetingData(){var data={};if(isAmazonApiAvailable()){data=amznads.getTargeting();if(!isObject(data))data={}}return data}var keyMap=function(){var map={};function has(id){return id in map}function addKey(id,key){if(!has(id))map[id]=[];map[id].push(key)}function getKeys(id){return has(id)?slice.call(map[id]):[]}function clearKeys(id){if(has(id)){map[id].length=0;return true}return false}return{has:has,clearKeys:clearKeys,getKeys:getKeys,addKey:addKey}}();function clearPreviousKeyValuePairs(player){var playerId=
player.getId();if(keyMap.has(playerId)){var keys=keyMap.getKeys(playerId);if(keys.length){log("clearing previous ad key-values: "+keys.join(", "));for(var i=0,endi=keys.length;i<endi;++i)player.setAdKeyValue(keys[i],null);keyMap.clearKeys(playerId)}}}function setAdKeyValue(player,key,value){log("setting ad key-value: "+key+' = "'+value+'"');keyMap.addKey(player.getId(),key);player.setAdKeyValue(key,value)}function handleTargetingData(player){var targeting=getTargetingData();clearPreviousKeyValuePairs(player);
for(var key in targeting){if(!hasOwn(targeting,key))continue;var val=targeting[key];if(val instanceof Array)for(var i=0,endi=val.length;i<endi;++i)setAdKeyValue(player,val[i],"1");else setAdKeyValue(player,key,val)}}function setAdKeyValuePairs(player){if(player.getPlayerType()!==CVP.FLASH)return;log("setAdKeyValuePairs(player)");handleTargetingData(player)}function init(config){if(inited)return;log("init(config)",config);inited=true;if(isObject(config)){if("amznkey"in config)amznkey=config.amznkey;
if("timeout"in config)timeoutForGetAdsCallback=config.timeout}requestAdRefresh(function(){log("init requestAdRefresh responded")})}function requireInit(fn){return function(){if(!inited){log("ERROR: init() must be called first!");return}fn.apply(this,arguments)}}return{requestAdRefresh:requireInit(requestAdRefresh),getTargetingData:requireInit(getTargetingData),setAdKeyValuePairs:requireInit(setAdKeyValuePairs),isAmazonApiAvailable:isAmazonApiAvailable,init:init}}();AmazonDirectMatchBuy.init();try{amzn_ads.getAds("3159")}catch(e){}
function crtg_getCookie(c_name){var i,x,y,ARRCookies=document.cookie.split(";");for(i=0;i<ARRCookies.length;i++){x=ARRCookies[i].substr(0,ARRCookies[i].indexOf("="));y=ARRCookies[i].substr(ARRCookies[i].indexOf("=")+1);x=x.replace(/^\s+|\s+$/g,"");if(x==c_name)return unescape(y)}return""}var crtg_cookiename="crtg_trnr";var crtg_varname="crtg_content";var crtg_nid="4157";var crtg_rnd=Math.floor(Math.random()*99999999999);
(function(){var crtg_url=location.protocol+"//rtax.criteo.com/delivery/rta/rta.js?netId="+escape(crtg_nid);crtg_url+="&cookieName="+escape(crtg_cookiename);crtg_url+="&rnd="+crtg_rnd;crtg_url+="&varName="+escape(crtg_varname);var crtg_script=document.createElement("script");crtg_script.type="text/javascript";crtg_script.src=crtg_url;crtg_script.async=true;if(document.getElementsByTagName("head").length>0)document.getElementsByTagName("head")[0].appendChild(crtg_script);else if(document.getElementsByTagName("body").length>
0)document.getElementsByTagName("body")[0].appendChild(crtg_script)})();var crtg_content=crtg_getCookie(crtg_cookiename);
